### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /home/cc/pointSIFT-master/tf_utils/tf_ops/pointSIFT_op/tf_pointSIFT_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by ZeweiXu** [MVIG-SJTU/pointSIFT#10]
I am using python2.7, Tensorflow1.4 and cuda8.0. I successfully complied the files in the four folders: sampling, pointSIFT_op, interpolation, and grouping. But when I run the training: python train_and_eval_scannet.py, the below error always pops up. Any help would be greatly appreciated!!!

/home/cc/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train_and_eval_scannet.py", line 14, in <module>
    import pointSIFT_pointnet as SEG_MODEL
  File "/home/cc/pointSIFT-master/models/pointSIFT_pointnet.py", line 6, in <module>
    from pointSIFT_util import pointSIFT_module, pointSIFT_res_module, pointnet_fp_module, pointnet_sa_module
  File "/home/cc/pointSIFT-master/tf_utils/pointSIFT_util.py", line 12, in <module>
    from pointSIFT_op import pointSIFT_select, pointSIFT_select_four
  File "/home/cc/pointSIFT-master/tf_utils/tf_ops/pointSIFT_op/pointSIFT_op.py", line 14, in <module>
    pointSIFT_module = tf.load_op_library(os.path.join(BASE_DIR, 'tf_pointSIFT_so.so'))
  File "/home/cc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/cc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/cc/pointSIFT-master/tf_utils/tf_ops/pointSIFT_op/tf_pointSIFT_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

**Comment by jmydurant** [comment]
Make sure:
1. path in compile file must fit the python you used (most likely). Double check your python env or anaconda path.
2. strongly recommend python3. For Tensorflow 1.4, you may not use CuDNN 9.1. Because it's too new for this tf version.

**Comment by chencidhao226342** [comment]
python3.6 and tensorflow1.8 cuda8.0, but it still has this problem, i have checked the path. what should I do? thanks!

**Comment by ZeweiXu** [comment]
Thank you for the answer, I reinstalled and use the exactly same Cuda, cudnn and tensorflow versions mentioned by the authors and it works.

**Comment by ashish-kubade** [comment]
Hi Team,
I am getting above error, and the solutions mentioned above, could not resolve my problem, hence I am posting here again.
I have checked the python, cuda and cudnn versions, which are python=3.5, cuda = 8.0, CuDNN = 7.0. 
 Could anyone please suggest me any workarounds if above configuration is valid.

TIA :)

**Comment by bodhicheng** [comment]
The problem is caused by the difference between the local and compiled gcc versions of tensorflow.
Conda's tensorflow is compiled by gcc7. My local version is 4.8. When I installed with pip, the problem was solved.

**Comment by dennisushi** [comment]
A similar error happened to me - I had to fix by reinstalling tensorflow-addons only. Reinstalling anything else did not help.
