### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by yanx27** [MVIG-SJTU/pointSIFT#27]
Hello, I use python 3.6.7 and tensorflow 1.8 with cuda 9.0, but miss this error. Do I have to use the same version as you？ Thanks :)

`>>> from tf_utils.pointSIFT_util import pointSIFT_module
/home/yxu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/yxu/Github/pointSIFT/tf_utils/pointSIFT_util.py", line 6, in <module>
    from tf_utils.tf_ops.pointSIFT_op.pointSIFT_op import pointSIFT_select, pointSIFT_select_four
  File "/data1/yxu/Github/pointSIFT/tf_utils/tf_ops/pointSIFT_op/pointSIFT_op.py", line 14, in <module>
    pointSIFT_module = tf.load_op_library(os.path.join(BASE_DIR, 'tf_pointSIFT_so.so'))
  File "/home/yxu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.9.0: cannot open shared object file: No such file or directory`

**Comment by Cogito2012** [comment]
@yanx27 
You can try to export the cuda 9.0 path to the environment variable `LD_LIBRARY_PATH`, like this:
`
export LD_LIBRARY_PATH="/usr/local/cuda-9.0/lib64"
`

**Comment by windtries** [comment]
hello,I meet the same error,I really want to know if you have solved the problem?@yanx27

**Comment by MrCrazyCrab** [comment]
@yanx27 have you solved the problem, i use tensorflow1.12.0, but i met the error just same as you.
