### ISSUE TITLE
NotFoundError: /home/yxh/pointSIFT-master/tf_utils/tf_ops/pointSIFT_op/tf_pointSIFT_so.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yangxh31** [MVIG-SJTU/pointSIFT#5]
ipdb> Traceback (most recent call last):

  File "<ipython-input-1-e75488c94c66>", line 1, in <module>
    debugfile('/home/yxh/pointSIFT-master/train_and_eval_scannet.py', wdir='/home/yxh/pointSIFT-master')

  File "/home/yxh/anaconda2/envs/tensorflow/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 728, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "/home/yxh/anaconda2/envs/tensorflow/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)

  File "<string>", line 1, in <module>

  File "/home/yxh/anaconda2/envs/tensorflow/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/yxh/anaconda2/envs/tensorflow/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/yxh/pointSIFT-master/train_and_eval_scannet.py", line 12, in <module>
    import models.pointSIFT_pointnet as SEG_MODEL

  File "/home/yxh/pointSIFT-master/models/pointSIFT_pointnet.py", line 6, in <module>
    from tf_utils.pointSIFT_util import pointSIFT_module, pointSIFT_res_module, pointnet_fp_module, pointnet_sa_module

  File "/home/yxh/pointSIFT-master/tf_utils/pointSIFT_util.py", line 6, in <module>
    from tf_utils.tf_ops.pointSIFT_op.pointSIFT_op import pointSIFT_select, pointSIFT_select_four

  File "/home/yxh/pointSIFT-master/tf_utils/tf_ops/pointSIFT_op/pointSIFT_op.py", line 14, in <module>
    pointSIFT_module = tf.load_op_library(os.path.join(BASE_DIR, 'tf_pointSIFT_so.so'))

  File "/home/yxh/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)

  File "/home/yxh/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))

**Comment by yangxh31** [comment]
I have solved this problem. The following similar operations need to be applied to other folders, too careless before.





Then, change the path in all the complie file, like tf_utils/tf_ops/sampling/tf_sampling_compile.sh Finally, compile the source file, we use tf_sampling as example.

    cd tf_utils/tf_ops/sampling
    chmod +x tf_sampling_compile.sh
    ./tf_sampling_compile.sh

**Comment by QuantumSeven** [comment]
Could you send me a copy of the compiled file? Thank you very much.
